### ISSUE TITLE
执行save方法插入的速度很慢

### ISSUE THREAD

**Issue by j328870247** [Joker-King/JKDBModel#37]
一千多条数据插入了10秒左右，主要耗时操作在插入数据库前json转字符那块，能否给出一个优化方案，谢谢

**Comment by 0xhellohaley** [comment]
这个库里好像没有json 转字符啊？你是指你从服务器返回的数据转换为Model这个过程么？
另外大量数据的保存，就不要一个对象一个对象的save了，使用数组来一次性存储更快。因为数组保存的方法使用的是事务处理。

**Comment by j328870247** [comment]
使用之前没有仔细全面的看model里的方法，后来发现了批量存储的方法，写的很棒，谢谢！
