### ISSUE TITLE
我刚刚在cocoachina提过了 不过我觉得这里靠谱我再提一下

### ISSUE THREAD

**Issue by Loxe** [Joker-King/JKDBModel#5]
刚刚我阅读了下源代码 写的很棒 可是我发现save和update 是用过insert into 和 update set的
sqlite其实是支持 replace into 的 相当于 存在就是update 不存在就是insert 这样可以将两个方法合并成一个 会比较清晰 嘿嘿

**Comment by Joker-King** [comment]
有的人喜欢将save和update合并，我是想有时候不存在主键，就不更新，也不做插入操作，所以才分开的，为的用起来方便还特意加了一个saveOrUpdate方法呢！不过还是谢谢你的建议

**Comment by Loxe** [comment]
:+1:   :]   原来如此 我没注意到这个方法 ~
