### ISSUE TITLE
我往数据库存入了NSData数据类型,但是取出来的data却是空的

### ISSUE THREAD

**Issue by CXTretar** [Joker-King/JKDBModel#53]
//
//  ViewController.m
//  FMDBTest
//
//  Created by Felix on 2017/7/13.
//  Copyright © 2017年 Felix. All rights reserved.
//

#import "ViewController.h"
#import "Person.h"
#import "Dog.h"
#import <JKDBHelper.h>

@interface ViewController ()

@property (nonatomic, strong) NSMutableArray *dataArray;

@end

@implementation ViewController

- (NSMutableArray *)dataArray {
    if (!_dataArray) {
        _dataArray = [NSMutableArray array];
    }
    return _dataArray;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    for (int i = 0; i < 20; i++) {
        Person *person = [Person new];
        person.age = i;
        NSMutableArray *temp = [NSMutableArray array];
        for (int j = 0; j < 10; j ++) {
            Dog *dog = [Dog new];
            dog.name = [NSString stringWithFormat:@"狗名%d", j];
            [temp addObject:dog];
        }
        person.dogs = temp.copy;
        [self.dataArray addObject:person];
    }
    
}

- (IBAction)insetData:(id)sender {
    
    for (Person *person in self.dataArray) {
        person.dogsData = [NSKeyedArchiver archivedDataWithRootObject:person.dogs];
    }
    [Person clearTable];
    [Person saveObjects:self.dataArray];
     NSLog(@"%@", [JKDBHelper dbPath]);
}

- (IBAction)printfData:(id)sender {
    self.dataArray = [Person findAll].copy;
    for (Person *person in self.dataArray) {
        person.dogs = [NSKeyedUnarchiver unarchiveObjectWithData:person.dogsData];
        NSLog(@"%ld", (long)person.age);
        for (Dog *dog in person.dogs) {
            NSLog(@"%@", dog.name);
            
        }
    }
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end

**Comment by 0xhellohaley** [comment]
数组不能存储。

At 2017-07-13 17:27:06, "misscxuan" <notifications@github.com> wrote:


`#import "ViewController.h"
#import "Person.h"
#import "Dog.h"
#import <JKDBHelper.h>

@interface ViewController ()

@property (nonatomic, strong) NSMutableArray *dataArray;

@EnD

@implementation ViewController

(NSMutableArray *)dataArray {
if (!_dataArray) {
_dataArray = [NSMutableArray array];
}
return _dataArray;
}

(void)viewDidLoad {
[super viewDidLoad];
for (int i = 0; i < 20; i++) {
Person *person = [Person new];
person.age = i;
NSMutableArray *temp = [NSMutableArray array];
for (int j = 0; j < 10; j ++) {
Dog *dog = [Dog new];
dog.name = [NSString stringWithFormat:@"狗名%d", j];
[temp addObject:dog];
}
person.dogs = temp.copy;
[self.dataArray addObject:person];
}

}

(IBAction)insetData:(id)sender {

for (Person *person in self.dataArray) {
person.dogsData = [NSKeyedArchiver archivedDataWithRootObject:person.dogs];
}
// [Person clearTable];
// [Person saveObjects:self.dataArray];
NSLog(@"%@", [JKDBHelper dbPath]);
}

(IBAction)printfData:(id)sender {
// self.dataArray = [Person findAll].copy;
for (Person *person in self.dataArray) {
person.dogs = [NSKeyedUnarchiver unarchiveObjectWithData:person.dogsData];
NSLog(@"%ld", (long)person.age);
for (Dog *dog in person.dogs) {
NSLog(@"%@", dog.name);

  }


}
}`

**Comment by CXTretar** [comment]
好的，我将数组转成json字符串，再将字符串存入数据库，用的时候再取出进行json解析，暂时解决了问题。
